import time

from base.Base import Base
import utils.CustomLogger as cl


class SurveyModule(Base):
    click_read_check_box = ('xpath', '//android.view.View[@text="Read"]/android.widget.CheckBox')
    click_workout_check_box = ('xpath', '//android.view.View[@text="Work out"]/android.widget.CheckBox')
    click_video_games_check_box = ('xpath', '//android.view.View[@text="Play video games"]/android.widget.CheckBox')
    click_free_time_next_button = ('xpath', '//android.widget.Button[@text="NEXT"]')
    click_spider_man_check_box = ('xpath', '//android.view.View[@text="Spider man ('
                                           'Avengers)"]/android.widget.RadioButton')
    click_superhero_next_button = ('xpath', '//android.widget.Button[@text="NEXT"]')
    click_outbreak_movie_button = ('xpath', '//android.view.View[@text="Outbreak"]/android.widget.RadioButton')
    click_movie_next_button = ('xpath', '//android.widget.Button[@text="NEXT"]')
    click_on_pick_date_button = ('xpath', '//android.widget.Button[@text="Pick a date"]')
    select_date = ('xpath', '//android.widget.TextView[@content-desc="Wed, Jan 17"]')
    confirm_date_button = ('id', 'com.example.compose.jetsurvey:id/confirm_button')
    date_next_button = ('xpath', '//android.widget.Button[@text="NEXT"]')
    selfie_rating_button = ('xpath', '//android.widget.SeekBar[@text="1.0"]')
    selfie_next_button = ('xpath', '//android.widget.Button[@text="NEXT"]')
    add_photo_button = ('xpath', '//android.widget.Button[@text="ADD PHOTO"]')
    click_photo_button = ('id', 'com.oplus.camera:id/shutter_button')
    done_photo_button = ('id', 'com.oplus.camera:id/done_button')
    done_selfie_button = ('xpath', '//android.widget.Button[@text="DONE"]')
    done_survey_button = ('xpath', '//android.widget.Button[@text="DONE"]')

    def survey_module(self):
        time.sleep(1)
        self.click(self.click_read_check_box)
        cl.allure_logs("Clicked on Read Check box")
        time.sleep(1)
        self.click(self.click_workout_check_box)
        cl.allure_logs("Clicked on workout Check box")
        time.sleep(1)
        self.click(self.click_video_games_check_box)
        cl.allure_logs("Clicked on video games check box")
        time.sleep(1)
        self.click(self.click_free_time_next_button)
        cl.allure_logs("Clicked on next button")
        time.sleep(1)
        self.click(self.click_spider_man_check_box)
        cl.allure_logs("Spider man selected")
        time.sleep(1)
        self.click(self.click_superhero_next_button)
        cl.allure_logs("clicked on next button")
        time.sleep(1)
        self.click(self.click_outbreak_movie_button)
        cl.allure_logs("Spider man selected")
        time.sleep(1)
        self.click(self.click_movie_next_button)
        cl.allure_logs("clicked on next button")
        time.sleep(1)
        self.click(self.click_on_pick_date_button)
        cl.allure_logs("clicked on pick a date button")
        time.sleep(1)
        self.click(self.select_date)
        cl.allure_logs("Date Selected")
        time.sleep(1)
        self.click(self.confirm_date_button)
        cl.allure_logs("clicked on ok button after selecting the date")
        time.sleep(1)
        self.click(self.date_next_button)
        cl.allure_logs("clicked on select date next button")
        time.sleep(1)
        self.click(self.selfie_rating_button)
        cl.allure_logs("selected selfie rating")
        time.sleep(1)
        self.click(self.selfie_next_button)
        cl.allure_logs("clicked on selfie next button")
        time.sleep(1)
        self.click(self.add_photo_button)
        cl.allure_logs("clicked on add photo button")
        time.sleep(2)
        self.click(self.click_photo_button)
        cl.allure_logs("clicked on camera button")
        time.sleep(2)
        self.click(self.done_photo_button)
        cl.allure_logs("clicked on done photo button")
        time.sleep(2)
        self.click(self.done_selfie_button)
        cl.allure_logs("clicked on done selfie button")
        time.sleep(2)
        self.click(self.done_survey_button)
        cl.allure_logs("clicked on done survey button")
